### ISSUE TITLE
Crucigrama definitivo

### ISSUE THREAD

**Issue by oscarotero** [mariaozamiz/crossword-ha#2]
Boas, pásoche o crucigrama definitivo. Faltan as definicións, podes usar mentras tanto as propias palabras como definición.

[CRUCI.HA.pdf](https://github.com/mariaozamiz/crossword-ha/files/5868831/CRUCI.HA.pdf)

**Comment by mariaozamiz** [comment]
Bo dia! 
Grazas pola info, agora abro nova rama para debuxalo! 
Miro que hai algunhas palabras do revés e teño un par de dúbidas. Por exemplo, no caso de "ESCORZO":
- Entendo que a pista será algo así como "(do revés) O cabalo crea profundidade grazas ao..." e que a numeración do label correspondente vai na derradeira letra, "O". E asi?
- Por outra banda, a función handleWriting funciona so de esquerda a dereita e de arriba abaixo. A nivel experiencia se me atopo unha palabra do revés, pode que intente escribila de atrás adiante. Daquela o handleWriting vai saltar unha cela e será molesto. Como poderiamos xestionalo?

**Comment by oscarotero** [comment]
- Si, cun "(do revés)" na descrición penso que sería suficiente.
- É complexo. Detectar se a palabra se escribe ao revés e se o usuario comezou a escribir dende a última letra para ir cara atrás, pode ser complicado e teño dúbidas se tanta "intelixencia" vai ser confusa para o usuario (que ve que lle salta o foco para sitios que quizáis non quería). Se vemos que esta funcionalidade non funciona ben a nivel de UX, case a eliminaría e faría que sexa o usuario coas flechas to teclado (ou o tabulador) o que vaia saltan de celdas. 
- E xa aproveitando, vexo que incluíches d.js como dependencia. Cando cho ensinei, era só para que viras exemplos de cómo se implementa un sistema de event delegation (que podes atopar [máis exemplos por internet](https://christianheilmann.com/2020/11/01/back-to-basics-event-delegation/)). Tamén ten un exemplo de creación de custom events, que [tamén podes ver noutros sitios](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) por se queres que o crucigrama lance eventos propios como "error", "success", etc. Pero eu non usaría d.js aquí, mellor que non haxa dependencias.

**Comment by mariaozamiz** [comment]
Concordo. Desboto esta funcionalidade do main e vou experimentando na póla flow-writting. Paréceme práctico no caso do móbil, se cadra pódese activar ou desactivar cun botón. Voulle dar unha volta :)

Retiro a dependencia tamén.

**Comment by oscarotero** [comment]
Aqui van as descricións:

HORIZONTALES
1. Cada una de las 12 partes de un año.. Lugar de nacimiento del autor de este maravilloso cuadro. 
2. Movimiento anti-arte, pro-vandalismo, ultra-gamberro nacido a principios del siglo XX. Museo donde está este extraordinario cuadro.
3. Yoko (…), artista conceptual perteneciente a Fluxus. Como no había competencia, lo que no le hace falta poner en el papel a Velázquez en este cuadro (ver esquina inferior derecha). Iniciales del artista y diseñador Pop ochentero que retrató a Joan Collins e hizo portadas para Duran Duran.
4. Sudeste. Relativo a Minias, rey beocio. Reza.
5. Teraesla. Negación. Al revés, mujeres dementes.
6. Objeto simbólico que se entrega en el cuadro, que es el centro de la composición. Nombre de esta web.
7. Ciudad que se rinde en este cuadro. Atreva.
8. Cuerpo mineral formado por dos o más cristales asociados simétricamente. Velázquez no era tanto de esto, era más de mancha. 
10. Animal recién nacido. Para los historiadores del arte, lo que se apoya en las jambas.
11. Acaricia ligeramente. Felipe (…), rey de España en la época y protector de Velázquez. Al revés, iniciales de doctora.
12. Esbozar una obra de arte. Tercera letra. 
12. Iniciales del principal escultor neoclásico. Tipo de perspectiva del paisaje holandés que veis al fondo. 
13. Iniciales de ese escultor Pop que hace réplicas a gran escala de objetos cotidianos. Película de 1963 de Andy Warhol donde se ve a un tipo comiendo. Velazquez pintó a uno: Don Sebastian de Morra.
14. Al revés, pose en la que está el caballo de la derecha, típico recurso barroco para introducirnos en el cuadro. 

VERTICALES

1. Años que duró la ciudad en manos españolas tras pintar Velázquez este cuadro. Iniciales del más ilustre pintor Bielorruso. Dios pintado por Velázquez en “Los borrachos”.
2. Este impresionista idolatraba a Velázquez. Velázquez está en el podio de este movimiento artístico.
3. Periodo japonés en el que florecieron las artes e influyó significativamente en el arte moderno occidental. El ejército español de Flandes que vemos a la derecha. 
4. Iniciales de una de las más excelsas manieristas italianas. Aunque no estuvo en la batalla, pintor representado en el extremo derecho.
5. Persona muerta. Oro. Iniciales del impresionista que nos regaló “El almuerzo de los remeros”, más de Rubens que de Velázquez.
6. General vencedor (y de muy buen ganar) además de amigo del autor. El hijo de Fidipo y padre del heraclida Tésalo.
7. Letra fuerte y capicúa. Pronuncié unas palabras. 
8. Nos dirigimos a ver este cuadro. Famoso Conde-Duque que apoyó a Velázquez en su carrera.
9. Para tener un billete de vuelta nos hace falta uno de estos. Tres simples letras indican falta o carencia de alguna cosa. Nombre de Pila de Magritte. 
10. Pronombre de la tercera persona en género masculino. Años que duró el conflicto entre España y Holanda aquí representado. Iniciales de nuestra impresionista danesa preferida.
11. Parte delantera de un barco. Al revés, tiene convicciones religiosas. 
12. Según Ortega y Gasset, cada “uno de los elementos que forman la columna vertebral de todo este cuadro”. Dramaturgo que escribió sobre el hecho histórico que vemos en la imagen.

**Comment by mariaozamiz** [comment]
Xa están incluidos no proxecto. A numeración a cambiei para adaptalo ao formato dixital.
